#
# Module manifest for module 'PwrSearch'
#
# Generated by: Oscar Calvo
#

@{

RootModule = 'PwrSearch.psm1'

NestedModules = @('SearchDir.dll')

ModuleVersion = '1.1.2' # x-release-please-version

GUID = '8c1d7a9e-5b2f-4e31-9c4d-6a7b8c9d0e1f'

Author = 'Oscar Calvo'

CompanyName = ''

Copyright = '(c) Oscar Calvo. All rights reserved.'

Description = 'Fast directory and file search backed by a native SearchDir.dll, plus a go navigation command.'

PowerShellVersion = '5.1'

ScriptsToProcess = @('build.ps1')

FunctionsToExport = 'Switch-Location', 'sd'

CmdletsToExport = 'Search-Directory', 'Get-RepoRoot'

VariablesToExport = @()

AliasesToExport = 'go'

FileList = 'CLAUDE.md', 'README.md', 'SearchDir.dll'

PrivateData = @{

    PSData = @{

        Tags = 'search','navigation','directory','powershell-tool'

        LicenseUri = 'https://github.com/ocalvo/PwrSearch/blob/master/LICENSE'

        ProjectUri = 'https://github.com/ocalvo/PwrSearch'

        ReleaseNotes = 'See full history: https://github.com/ocalvo/PwrSearch/blob/master/CHANGELOG.md'

    }

}

}
